---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carlos-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carlos-web
  template:
    metadata:
      labels:
        app: carlos-web
    spec:
      containers:
        - name: carlos-web
          image: 210486000475.dkr.ecr.us-east-1.amazonaws.com/carlos-web:2.0
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - mountPath: "/var/www/html"
              name: php-storage
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: php-storage
          persistentVolumeClaim:
            claimName: php-pvc
