aws_region                   = "us-east-1"
vpc1_cidr_block              = "10.0.0.0/16"
vpc1_public_subnet_cidr      = "10.0.1.0/24"
vpc1_private_subnet_cidr     = "10.0.2.0/24"
vpc2_cidr_block              = "10.1.0.0/16"
vpc2_private_subnet_cidr     = "10.1.1.0/24"
availability_zone1           = "us-east-1a"
availability_zone2           = "us-east-1b"
allowed_cidr                = "0.0.0.0/0"  # Este CIDR debería estar restringido a tu IP de origen para producción
instance_ami                 = "ami-064519b8c76274859"
instance_type               = "t2.micro"
key_name                    = "clave-ftp2"
user_data                   = "script.sh"
bastion_ip                  = "192.168.1.100/32"  # Sustituir con la IP permitida para acceder al bastión
s3_bucket_name              = "s3-carlosbullejos2-bucket"  # Nombre del bucket de S3
ftp_container_name          = "ftp-storage"  # Nombre del contenedor FTP que usará el bucket
