name: Terraform AWS Infrastructure Management

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select action to perform'
        required: true
        default: 'apply'
        options:
          - apply
          - destroy

jobs:
  terraform-apply:
    if: ${{ github.event.inputs.action == 'apply' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1" # Cambia a la región de AWS que estás usando
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Terraform Init
        run: terraform init
        working-directory: vpcs

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: vpcs

      - name: Upload terraform state
        uses: actions/upload-artifact@v4
        with:
          name: terraform_state
          path: vpcs/terraform.tfstate

  terraform-destroy:
    if: ${{ github.event.inputs.action == 'destroy' }}
    runs-on: ubuntu-latest
    needs: terraform-apply
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download terraform state
        uses: actions/download-artifact@v4
        with:
          name: terraform_state
          path: vpcs

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Terraform Init
        run: terraform init
        working-directory: vpcs

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: vpcs
