name: Destroy AWS Infrastructure

on:
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde la interfaz de GitHub

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN}}
          aws-region: "us-east-1"

      - name: Initialize Terraform
        run: terraform init
        working-directory: vpcs

      - name: Terraform Destroy
        run: |
         terraform destroy -auto-approve \
         -var "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" \
         -var "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
         -var "aws_session_token=${{ secrets.AWS_SESSION_TOKEN }}" \
         -var "public_key=${{ secrets.SSH_PUBLIC_KEY }}"
        working-directory: vpcs

      - name: Upload Terraform State to S3 (if needed)
        run: |
          aws s3 cp vpcs/terraform.tfstate s3://s3-carlosbullejos2-bucket/terraform.tfstate
        working-directory: vpcs

