name: Destroy Terraform AWS Deployment

on:
  workflow_dispatch:
    # Esto permite ejecutar manualmente el workflow de destrucción

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download terraform state
        uses: actions/download-artifact@v4
        with:
          name: terraform_state
          path: vpcs

      - name: instalar terraform
        uses: hashicorp/setup-terraform@v3

      - name: credentials aws configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1" # Cambia a la región de AWS que estás usando
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: init terraform
        run: terraform init
        working-directory: vpcs

      - name: destroy terraform
        run: terraform destroy -auto-approve
        working-directory: vpcs
