name: proftpd_ldap

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: "us-east-1"

      - name: Terraform Init
        run: terraform init
        working-directory: ./vpcs

      - name: Terraform Plan
        run: terraform plan -var "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" -var "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -var "aws_session_token=${{ secrets.AWS_SESSION_TOKEN }}" -var "public_key=${{ secrets.SSH_PUBLIC_KEY }}"
        working-directory: ./vpcs

      - name: Terraform Apply
        run: terraform apply -auto-approve -var "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" -var "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -var "aws_session_token=${{ secrets.AWS_SESSION_TOKEN }}" -var "public_key=${{ secrets.SSH_PUBLIC_KEY }}"
        working-directory: ./vpcs

      # Guardar el archivo terraform.tfstate como artefacto
      - name: Upload Terraform State as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform_state
          path: ./vpcs/terraform.tfstate

  upload_to_s3:
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: "us-east-1"

      # Descargar el artefacto terraform.tfstate y guardarlo en la caché
      - name: Download Terraform State Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform_state
          path: ./terraform_cache

      # Mover el archivo descargado al nombre esperado para subirlo a S3
      - name: Move State File to Root Directory
        run: mv ./terraform_cache/terraform.tfstate terraform.tfstate

      - name: Subir estado de Terraform a S3
        run: |
          aws s3 cp vpcs/terraform.tfstate s3://s3-carlosbullejos2-bucket/terraform.tfstate
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"  # Cambia a la región de AWS que estás usando
