name: Terraform AWS Deployment

on:
  push:
    branches:
      - vpcs

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"  # Cambia a la regi칩n de AWS que est치s usando
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Configurar clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Inicializar Terraform
        run: terraform init
        working-directory: vpcs

  
      - name: Aplicar Terraform
        run: terraform apply -auto-approve
        working-directory: vpcs

      - name: Subir estado de Terraform a S3
        run: |
          aws s3 cp vpcs/terraform.tfstate s3://s3-carlosbullejos2-bucket/terraform.tfstate
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"  # Cambia a la regi칩n de AWS que est치s usando

